name: Test Coverage Suite
on:
  pull_request:
    branches:
      - main
      - develop 
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - develop 

jobs:
  build-client:
    name: Build and Test Client
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install server dependencies
        run: cd client && npm install

      - name: Run Tests
        run: npm test -- --watchAll